from pathlib import Path

path = Path("telegram_bot.py")
text = path.read_text(encoding="utf-8")

old_parse = '''def parse_link(value):\n    match = re.match(r"^https?://(?:www\\.)?t\\.me/(?:c/(\\d+)|([A-Za-z0-9_]{3,}))/([0-9]+)(?:\\?.*)?$", value.strip())\n    if not match:\n        raise ValueError("Invalid Telegram message link.")\n    private, username, mid = match.groups()\n    return (f"-100{private}" if private else f"@{username}"), int(mid)\n'''
new_parse = '''def parse_link(value):\n    match = re.match(r"^https?://(?:www\\.)?t\\.me/(?:c/(\\d+)|([A-Za-z0-9_]{3,}))/([0-9]+)(?:\\?.*)?$", value.strip())\n    if not match:\n        raise ValueError("Invalid Telegram message link.")\n    private, username, mid = match.groups()\n    return (f"-100{private}" if private else f"@{username}"), int(mid)\n\ndef parse_bulk_link(value):\n    # Accept: t.me/c/123/471-480 and t.me/c/123/471 480\n    match = re.match(\n        r"^https?://(?:www\\.)?t\\.me/(?:c/(\\d+)|([A-Za-z0-9_]{3,}))/(\\d+)\\s*(?:-|\\s)\\s*(\\d+)(?:\\?.*)?$",\n        value.strip(),\n    )\n    if not match:\n        return None\n    private, username, start_text, end_text = match.groups()\n    start_id, end_id = int(start_text), int(end_text)\n    if start_id <= 0 or end_id < start_id:\n        raise ValueError("Invalid Telegram message ID range.")\n    count = end_id - start_id + 1\n    if count > MAX_BULK_MESSAGES:\n        raise ValueError(f"Maximum range is {MAX_BULK_MESSAGES} messages.")\n    peer = f"-100{private}" if private else f"@{username}"\n    return peer, start_id, end_id\n'''
if old_parse not in text:
    raise SystemExit("parse_link block not found")
text = text.replace(old_parse, new_parse, 1)

old_text = '''    if not re.match(r"^https?://(?:www\\.)?t\\.me/", text):\n        return await message.answer("Send a Telegram t.me message link or use the buttons below.", reply_markup=menu())\n    if not destination(uid):\n        return await message.answer("Set a destination first with 🎯 Destination.", reply_markup=menu())\n    status = await message.answer("🔎 Scanning message...", reply_markup=menu())\n    try:\n        await ensure_user_client()\n        peer, mid = parse_link(text)\n        await status.edit_text("🔎 Resolving Telegram channel...", reply_markup=menu())\n        source = await resolve_message_peer(peer)\n        await status.edit_text("🔎 Fetching message...", reply_markup=menu())\n        msg = await asyncio.wait_for(user_client.get_messages(source, ids=mid), timeout=SCAN_TIMEOUT_SECONDS)\n        if not msg or not getattr(msg, "media", None):\n            return await status.edit_text("That message does not contain downloadable media.", reply_markup=menu())\n        await create_job(uid, source, [msg], status)\n    except asyncio.TimeoutError:\n        await status.edit_text("⏱️ Telegram did not respond within the scan timeout. Check that the logged-in account can open this channel, then try again.", reply_markup=menu())\n    except (ValueError, RPCError) as exc:\n        await status.edit_text(f"Could not resolve that message: {exc}", reply_markup=menu())\n    except Exception as exc:\n        print(f"Scan failed: {type(exc).__name__}: {exc}", flush=True)\n        await status.edit_text(f"❌ Scan failed: {type(exc).__name__}: {exc}", reply_markup=menu())\n'''
new_text = '''    if not re.match(r"^https?://(?:www\\.)?t\\.me/", text):\n        return await message.answer("Send a Telegram t.me message link or use the buttons below.", reply_markup=menu())\n    if not destination(uid):\n        return await message.answer("Set a destination first with 🎯 Destination.", reply_markup=menu())\n\n    bulk = parse_bulk_link(text)\n    status = await message.answer("🔎 Scanning bulk messages..." if bulk else "🔎 Scanning message...", reply_markup=menu())\n    try:\n        await ensure_user_client()\n        if bulk:\n            peer, start_id, end_id = bulk\n            await status.edit_text(f"🔎 Resolving Telegram channel...\\n📦 Range: {start_id}–{end_id}", reply_markup=menu())\n            source = await resolve_message_peer(peer)\n            await status.edit_text(f"🔎 Fetching messages {start_id}–{end_id}...", reply_markup=menu())\n            msgs = await asyncio.wait_for(\n                user_client.get_messages(source, ids=list(range(start_id, end_id + 1))),\n                timeout=SCAN_TIMEOUT_SECONDS,\n            )\n            media_msgs = [msg for msg in msgs if msg and getattr(msg, "media", None)]\n            await create_job(uid, source, media_msgs, status)\n            return\n\n        peer, mid = parse_link(text)\n        await status.edit_text("🔎 Resolving Telegram channel...", reply_markup=menu())\n        source = await resolve_message_peer(peer)\n        await status.edit_text("🔎 Fetching message...", reply_markup=menu())\n        msg = await asyncio.wait_for(user_client.get_messages(source, ids=mid), timeout=SCAN_TIMEOUT_SECONDS)\n        if not msg or not getattr(msg, "media", None):\n            return await status.edit_text("That message does not contain downloadable media.", reply_markup=menu())\n        await create_job(uid, source, [msg], status)\n    except asyncio.TimeoutError:\n        await status.edit_text("⏱️ Telegram did not respond within the scan timeout. Check that the logged-in account can open this channel, then try again.", reply_markup=menu())\n    except (ValueError, RPCError) as exc:\n        await status.edit_text(f"Could not resolve that message: {exc}", reply_markup=menu())\n    except Exception as exc:\n        print(f"Scan failed: {type(exc).__name__}: {exc}", flush=True)\n        await status.edit_text(f"❌ Scan failed: {type(exc).__name__}: {exc}", reply_markup=menu())\n'''
if old_text not in text:
    raise SystemExit("text scan block not found")
text = text.replace(old_text, new_text, 1)

# Improve prompts for the button and help text.
text = text.replace(
    'await message.answer("🔗 Send the Telegram message link (t.me/.../message_id).", reply_markup=menu())',
    'await message.answer("🔗 Send a Telegram link. For bulk use .../471-480 or .../471 480.", reply_markup=menu())',
    1,
)
text = text.replace(
    '"HJ GROUPS Media Collector\\n\\n🔗 Scan Link — send a Telegram message link.\\n📦 Bulk Range — send: @channel START_ID END_ID.',
    '"HJ GROUPS Media Collector\\n\\n🔗 Scan Link — send a Telegram message link. Bulk links like .../471-480 or .../471 480 are supported.\\n📦 Bulk Range — send: @channel START_ID END_ID.',
    1,
)

path.write_text(text, encoding="utf-8")
print("Applied bulk Telegram link support.")
