from pathlib import Path

p = Path("telegram_bot.py")
s = p.read_text(encoding="utf-8")

anchor = 'MAX_ACTIVE_JOBS = max(1, int(os.getenv("TELEGRAM_MAX_ACTIVE_JOBS", "1")))\n'
insert = anchor + 'SCAN_TIMEOUT_SECONDS = max(10, int(os.getenv("TELEGRAM_SCAN_TIMEOUT_SECONDS", "35")))\n'
if 'SCAN_TIMEOUT_SECONDS' not in s:
    if anchor not in s:
        raise SystemExit("config anchor not found")
    s = s.replace(anchor, insert, 1)

old = '''async def rebuild(session):\n    global user_client\n    if user_client.is_connected():\n        await user_client.disconnect()\n    user_client = TelegramClient(StringSession(session), API_ID, API_HASH)\n    await user_client.connect()\n\n'''
new = '''async def rebuild(session):\n    global user_client\n    if user_client.is_connected():\n        await user_client.disconnect()\n    user_client = TelegramClient(StringSession(session), API_ID, API_HASH)\n    await asyncio.wait_for(user_client.connect(), timeout=SCAN_TIMEOUT_SECONDS)\n\nasync def ensure_user_client():\n    session = await saved_session()\n    if not session:\n        raise RuntimeError("No saved Telegram session. Press 🔐 Login first.")\n    if not user_client.is_connected():\n        await rebuild(session)\n    authorized = await asyncio.wait_for(user_client.is_user_authorized(), timeout=SCAN_TIMEOUT_SECONDS)\n    if not authorized:\n        raise RuntimeError("Telegram session is no longer authorized. Press 🔐 Login first.")\n\nasync def resolve_message_peer(peer):\n    # For t.me/c/<internal-id>/<message-id>, Telegram gives only the marked chat ID.\n    # Telethon can resolve a negative -100... ID from its entity cache. If the entity\n    # is not cached, walk dialogs until the matching channel/chat is found.\n    try:\n        return await asyncio.wait_for(user_client.get_input_entity(peer), timeout=SCAN_TIMEOUT_SECONDS)\n    except (ValueError, TypeError):\n        target_id = int(peer) if str(peer).lstrip("-").isdigit() else None\n        if target_id is None:\n            return await asyncio.wait_for(user_client.get_entity(peer), timeout=SCAN_TIMEOUT_SECONDS)\n        async def find_in_dialogs():\n            async for dialog in user_client.iter_dialogs():\n                entity = getattr(dialog, "entity", None)\n                if entity is not None and getattr(entity, "id", None) == abs(target_id) and getattr(dialog, "id", None) == target_id:\n                    return entity\n            return None\n        entity = await asyncio.wait_for(find_in_dialogs(), timeout=SCAN_TIMEOUT_SECONDS)\n        if entity is None:\n            raise ValueError(f"Telegram channel/chat {peer} is not in the logged-in account's dialogs. Make sure the account has access to that channel.")\n        return entity\n\n'''
if old not in s:
    raise SystemExit("rebuild block not found")
s = s.replace(old, new, 1)

old_scan = '''    status = await message.answer("🔎 Scanning message...", reply_markup=menu())\n    try:\n        peer, mid = parse_link(text)\n        source = await user_client.get_entity(peer)\n        msg = await user_client.get_messages(source, ids=mid)\n        if not msg or not getattr(msg, "media", None):\n            return await status.edit_text("That message does not contain downloadable media.", reply_markup=menu())\n        await create_job(uid, source, [msg], status)\n    except (ValueError, RPCError) as exc:\n        await status.edit_text(f"Could not resolve that message: {exc}", reply_markup=menu())\n'''
new_scan = '''    status = await message.answer("🔎 Scanning message...", reply_markup=menu())\n    try:\n        await ensure_user_client()\n        peer, mid = parse_link(text)\n        await status.edit_text("🔎 Resolving Telegram channel...", reply_markup=menu())\n        source = await resolve_message_peer(peer)\n        await status.edit_text("🔎 Fetching message...", reply_markup=menu())\n        msg = await asyncio.wait_for(user_client.get_messages(source, ids=mid), timeout=SCAN_TIMEOUT_SECONDS)\n        if not msg or not getattr(msg, "media", None):\n            return await status.edit_text("That message does not contain downloadable media.", reply_markup=menu())\n        await create_job(uid, source, [msg], status)\n    except asyncio.TimeoutError:\n        await status.edit_text("⏱️ Telegram did not respond within the scan timeout. Check that the logged-in account can open this channel, then try again.", reply_markup=menu())\n    except (ValueError, RPCError) as exc:\n        await status.edit_text(f"Could not resolve that message: {exc}", reply_markup=menu())\n    except Exception as exc:\n        print(f"Scan failed: {type(exc).__name__}: {exc}", flush=True)\n        await status.edit_text(f"❌ Scan failed: {type(exc).__name__}: {exc}", reply_markup=menu())\n'''
if old_scan not in s:
    raise SystemExit("single scan block not found")
s = s.replace(old_scan, new_scan, 1)

old_range = '''        source = await user_client.get_entity(parts[1])\n        status = await message.answer("🔎 Scanning messages...", reply_markup=menu())\n        msgs = await user_client.get_messages(source, ids=list(range(start_id, end_id + 1)))\n        await create_job(uid, source, [msg for msg in msgs if msg and getattr(msg, "media", None)], status)\n    except (ValueError, RPCError) as exc:\n        await message.answer(f"Could not scan range: {exc}", reply_markup=menu())\n'''
new_range = '''        await ensure_user_client()\n        source = await asyncio.wait_for(user_client.get_entity(parts[1]), timeout=SCAN_TIMEOUT_SECONDS)\n        status = await message.answer("🔎 Scanning messages...", reply_markup=menu())\n        msgs = await asyncio.wait_for(user_client.get_messages(source, ids=list(range(start_id, end_id + 1))), timeout=SCAN_TIMEOUT_SECONDS)\n        await create_job(uid, source, [msg for msg in msgs if msg and getattr(msg, "media", None)], status)\n    except asyncio.TimeoutError:\n        await message.answer("⏱️ Telegram did not respond within the scan timeout. Please try the range again.", reply_markup=menu())\n    except (ValueError, RPCError) as exc:\n        await message.answer(f"Could not scan range: {exc}", reply_markup=menu())\n    except Exception as exc:\n        print(f"Range scan failed: {type(exc).__name__}: {exc}", flush=True)\n        await message.answer(f"❌ Range scan failed: {type(exc).__name__}: {exc}", reply_markup=menu())\n'''
if old_range not in s:
    raise SystemExit("range scan block not found")
s = s.replace(old_range, new_range, 1)

p.write_text(s, encoding="utf-8")
print("patched telegram_bot.py")
