from pathlib import Path
p = Path('telegram_bot.py')
s = p.read_text(encoding='utf-8')
old = '''    bulk = parse_bulk_link(text)\n    status = await message.answer("🔎 Scanning bulk messages..." if bulk else "🔎 Scanning message...", reply_markup=menu())\n    try:\n        await ensure_user_client()\n        if bulk:\n            peer, start_id, end_id = bulk\n            await status.edit_text(f"🔎 Resolving Telegram channel…\\n📦 Range: {start_id}–{end_id}", reply_markup=menu())\n            source = await asyncio.wait_for(resolve_message_peer(peer), timeout=SCAN_TIMEOUT_SECONDS)\n            await status.edit_text(f"🔎 Fetching messages {start_id}–{end_id}…", reply_markup=menu())\n            msgs = await asyncio.wait_for(\n                user_client.get_messages(source, ids=list(range(start_id, end_id + 1))),\n                timeout=SCAN_TIMEOUT_SECONDS,\n            )\n            media_msgs = [msg for msg in msgs if msg and getattr(msg, "media", None)]\n            await create_job(uid, source, media_msgs, status)\n            return\n\n        peer, mid = parse_link(text)\n        await status.edit_text(f"🔎 Resolving Telegram channel…\\n📌 Message: {mid}", reply_markup=menu())\n        source = await asyncio.wait_for(resolve_message_peer(peer), timeout=SCAN_TIMEOUT_SECONDS)\n        await status.edit_text(f"🔎 Fetching message {mid}…", reply_markup=menu())\n        msg = await asyncio.wait_for(user_client.get_messages(source, ids=mid), timeout=SCAN_TIMEOUT_SECONDS)\n        if not msg or not getattr(msg, "media", None):\n            return await status.edit_text("That message does not contain downloadable media.", reply_markup=menu())\n        await create_job(uid, source, [msg], status)\n    except asyncio.TimeoutError:\n        await status.edit_text("⏱️ Scan timed out after 35 seconds.\\n\\nCheck that the logged-in Telegram account can open this channel and try again.", reply_markup=menu())\n    except (ValueError, RPCError) as exc:\n        await status.edit_text(f"Could not resolve that message: {exc}", reply_markup=menu())\n'''
new = '''    bulk = parse_bulk_link(text)\n    status = await message.answer("🔎 Starting bulk scan…" if bulk else "🔎 Starting scan…", reply_markup=menu())\n\n    async def safe_status(text):\n        try:\n            await asyncio.wait_for(status.edit_text(text, reply_markup=menu()), timeout=8)\n        except Exception as exc:\n            print(f"[Voroa] Status update failed: {type(exc).__name__}: {exc}", flush=True)\n\n    async def bounded(coro, timeout=SCAN_TIMEOUT_SECONDS):\n        task = asyncio.create_task(coro)\n        try:\n            return await asyncio.wait_for(task, timeout=timeout)\n        except asyncio.TimeoutError:\n            task.cancel()\n            try:\n                await asyncio.wait_for(task, timeout=2)\n            except Exception:\n                pass\n            try:\n                if user_client.is_connected():\n                    await asyncio.wait_for(user_client.disconnect(), timeout=5)\n            except Exception:\n                pass\n            raise\n\n    try:\n        await safe_status("🔐 Checking Telegram session…")\n        await bounded(ensure_user_client())\n        if bulk:\n            peer, start_id, end_id = bulk\n            await safe_status(f"🔎 Resolving Telegram channel…\\n📦 Range: {start_id}–{end_id}")\n            source = await bounded(resolve_message_peer(peer))\n            await safe_status(f"🔎 Fetching messages {start_id}–{end_id}…")\n            msgs = await bounded(user_client.get_messages(source, ids=list(range(start_id, end_id + 1))))\n            media_msgs = [msg for msg in msgs if msg and getattr(msg, "media", None)]\n            await create_job(uid, source, media_msgs, status)\n            return\n\n        peer, mid = parse_link(text)\n        await safe_status(f"🔎 Resolving Telegram channel…\\n📌 Message: {mid}")\n        source = await bounded(resolve_message_peer(peer))\n        await safe_status(f"🔎 Fetching message {mid}…")\n        msg = await bounded(user_client.get_messages(source, ids=mid))\n        if not msg or not getattr(msg, "media", None):\n            return await safe_status("That message does not contain downloadable media.")\n        await create_job(uid, source, [msg], status)\n    except asyncio.TimeoutError:\n        await safe_status("⏱️ Telegram scan timed out after 35 seconds.\\n\\nThe scan was stopped safely instead of hanging. Check that the logged-in Telegram account can access this channel, then try again.")\n    except (ValueError, RPCError) as exc:\n        await safe_status(f"Could not resolve that message: {exc}")\n'''
if old not in s:
    raise SystemExit('target scan block not found')
s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')
print('bulk scan hardened')